# !file này thiết lập tự động buil,deploy,build run,tên,run
  version: '3'


  services:
    shop-shoe-api:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: shop-shoe-api-1
      restart: unless-stopped
      env_file:
            - .env
      ports: 
        - '5000:5000'   
    
  
    frontend:
      build: 
        context: ./frontend
        dockerfile: ./frontend/Dockerfile
      container_name: frontend
      restart: unless-stopped
      ports: 
        - '3000:3000'
      volumes:
      - ./frontend/src:/app/src   
      depends_on:
      - shop-shoe-api


    

  
