//!Utils
import {
  getProducts,
  getProfiles,
  getAllUser,
  getAllAdmin,
  AddToCart,
  TranSuccess,
  UploadImg,
  DestroyImg,
  AddProduct,
  UpdateProduct,
  UpdateUser,
  updateUserAdmin,
  deleteUserAdmin,
  deleteProduct,
} from "../utils/Api";
export {
  getProducts,
  getProfiles,
  getAllUser,
  getAllAdmin,
  AddToCart,
  TranSuccess,
  UploadImg,
  DestroyImg,
  AddProduct,
  UpdateProduct,
  UpdateUser,
  updateUserAdmin,
  deleteUserAdmin,
  deleteProduct,
};
